    # defaults:
    #     origin_regex: true
    #     allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
    #     allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    #     allow_headers: ['Content-Type', 'Authorization']
    #     max_age: 3600
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        # '^/': ~
        '^/':
                allow_origin: ['*']
                allow_headers: ['X-Custom-Auth']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
